#!/usr/bin/env bash


XAUTH=/tmp/.docker.xauth
if [ ! -f $XAUTH ]
then
    xauth_list=$(xauth nlist :0 | sed -e 's/^..../ffff/')
    if [ ! -z "$xauth_list" ]
    then
        echo $xauth_list | xauth -f $XAUTH nmerge -
    else
        touch $XAUTH
    fi
    chmod a+r $XAUTH
fi

docker run -it --rm \
  --runtime="nvidia" \
  --env="DISPLAY" \
  --env XAUTHORITY=$XAUTH \
  --volume "$XAUTH:$XAUTH" \
  --volume "/tmp/.X11-unix:/tmp/.X11-unix" \
  --volume "$PWD/../../../../../moveo:/home/docker/moveo" \
  --privileged \
  --net=host \
  --security-opt seccomp=unconfined \
  --user=docker \
  -w /home/docker/moveo \
  moveo_kinetic \
  bash
